import pygame


# Brown minotaur images
brown_minotaur_images = []
# 0 = Walk right
# 1 = Dying right
# 2 = Walk left
# 3 = Dying left

# Walk right
brown_minotaur_images.append([pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(1).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(2).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(3).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(4).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(5).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(6).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(7).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(8).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(9).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(10).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(11).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(12).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(13).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(14).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(15).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(16).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(17).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(R)(18).png')])

# Dying right
brown_minotaur_images.append([pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(1)R.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(2)R.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(3)R.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(4)R.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(5)R.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(6)R.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(7)R.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(8)R.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(9)R.png')])

# Walk left
brown_minotaur_images.append([pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(1).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(2).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(3).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(4).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(5).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(6).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(7).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(8).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(9).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(10).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(11).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(12).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(13).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(14).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(15).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(16).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(17).png'),pygame.image.load('images\enemies\\brown-minotaur\Minotaur-Walk(L)(18).png')])

# Dying left
brown_minotaur_images.append([pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(1)L.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(2)L.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(3)L.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(4)L.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(5)L.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(6)L.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(7)L.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(8)L.png'),pygame.image.load('images\enemies\\brown-minotaur\MinotaurDying(9)L.png')])