import pygame
# Player images
player_image_walk_right = [pygame.image.load('images\main-character\Run (1)R.png'),pygame.image.load('images\main-character\Run (2)R.png'),pygame.image.load('images\main-character\Run (3)R.png'),pygame.image.load('images\main-character\Run (4)R.png'),pygame.image.load('images\main-character\Run (5)R.png'),pygame.image.load('images\main-character\Run (6)R.png'),pygame.image.load('images\main-character\Run (7)R.png')]
player_image_stand_right = pygame.image.load('images\main-character\Idle (1)R.png')
player_image_shoot_right = [pygame.image.load('images\main-character\Shoot (1)R.png'),pygame.image.load('images\main-character\Shoot (2)R.png'),pygame.image.load('images\main-character\Shoot (3)R.png')]
player_image_jump_right = [pygame.image.load('images\main-character\Jump (1)R.png'),pygame.image.load('images\main-character\Jump (2)R.png'),pygame.image.load('images\main-character\Jump (3)R.png'),pygame.image.load('images\main-character\Jump (4)R.png'),pygame.image.load('images\main-character\Jump (5)R.png'),pygame.image.load('images\main-character\Jump (6)R.png'),pygame.image.load('images\main-character\Jump (7)R.png'),pygame.image.load('images\main-character\Jump (8)R.png'),pygame.image.load('images\main-character\Jump (9)R.png'),pygame.image.load('images\main-character\Jump (10)R.png')]
player_image_dead_right = [pygame.image.load('images\main-character\Dead (1)R.png'),pygame.image.load('images\main-character\Dead (2)R.png'),pygame.image.load('images\main-character\Dead (3)R.png'),pygame.image.load('images\main-character\Dead (4)R.png'),pygame.image.load('images\main-character\Dead (5)R.png'),pygame.image.load('images\main-character\Dead (6)R.png'),pygame.image.load('images\main-character\Dead (7)R.png'),pygame.image.load('images\main-character\Dead (8)R.png'),pygame.image.load('images\main-character\Dead (9)R.png'),]
player_image_walk_left = [pygame.image.load('images\main-character\Run (1)L.png'),pygame.image.load('images\main-character\Run (2)L.png'),pygame.image.load('images\main-character\Run (3)L.png'),pygame.image.load('images\main-character\Run (4)L.png'),pygame.image.load('images\main-character\Run (5)L.png'),pygame.image.load('images\main-character\Run (6)L.png'),pygame.image.load('images\main-character\Run (7)L.png')]
player_image_stand_left = pygame.image.load('images\main-character\Idle (1)L.png')
player_image_shoot_left = [pygame.image.load('images\main-character\Shoot (1)L.png'),pygame.image.load('images\main-character\Shoot (2)L.png'),pygame.image.load('images\main-character\Shoot (3)L.png')]
player_image_jump_left = [pygame.image.load('images\main-character\Jump (1)L.png'),pygame.image.load('images\main-character\Jump (2)L.png'),pygame.image.load('images\main-character\Jump (3)L.png'),pygame.image.load('images\main-character\Jump (4)L.png'),pygame.image.load('images\main-character\Jump (5)L.png'),pygame.image.load('images\main-character\Jump (6)L.png'),pygame.image.load('images\main-character\Jump (7)L.png'),pygame.image.load('images\main-character\Jump (8)L.png'),pygame.image.load('images\main-character\Jump (9)L.png'),pygame.image.load('images\main-character\Jump (10)R.png')]
player_image_dead_left = [pygame.image.load('images\main-character\Dead (1)L.png'),pygame.image.load('images\main-character\Dead (2)L.png'),pygame.image.load('images\main-character\Dead (3)L.png'),pygame.image.load('images\main-character\Dead (4)L.png'),pygame.image.load('images\main-character\Dead (5)L.png'),pygame.image.load('images\main-character\Dead (6)L.png'),pygame.image.load('images\main-character\Dead (7)L.png'),pygame.image.load('images\main-character\Dead (8)L.png'),pygame.image.load('images\main-character\Dead (9)L.png'),]